#!/usr/bin/env node
// tooling/pairing-pipeline/merge.mjs
//
// Folds mined edges (output/proposed-pairings.json) into src/data/pairingMeta.ts, tagged
// `recipenlg` with their 0-10 strength. Leaves src/data/flavorPairings.ts (the chef-canon
// `flavorbible` source) untouched — buildFlavorMap unions the two.
//
// Edges below --min-strength are dropped as generic co-occurrence noise.
//
// Usage:
//   node merge.mjs [--min-strength 2] [--dry-run]
//
// Re-runnable: regenerates the pairingMeta object literal from scratch each time, so it's
// idempotent for a given proposed-pairings.json + threshold.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..', '..');

const args = process.argv.slice(2);
const getArg = (name, def) => {
  const i = args.indexOf(`--${name}`);
  return i >= 0 && args[i + 1] && !args[i + 1].startsWith('--') ? args[i + 1] : def;
};
const MIN_STRENGTH = Number(getArg('min-strength', '2'));
const DRY = args.includes('--dry-run');

const proposed = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'output', 'proposed-pairings.json'), 'utf8'),
);

const pairKey = (a, b) => (a <= b ? `${a},${b}` : `${b},${a}`);

// Filter + dedupe by canonical key (keep highest strength if duplicated).
// Combined edge store: key -> { sources:Set, strength }. strength = max across sources.
const edges = new Map();
const addEdge = (a, b, source, strength) => {
  if (a === b) return;
  const k = pairKey(a, b);
  let e = edges.get(k);
  if (!e) { e = { sources: new Set(), strength: 0 }; edges.set(k, e); }
  e.sources.add(source);
  if (strength > e.strength) e.strength = strength;
};

// 1. recipenlg edges (filtered by --min-strength).
let recipeCount = 0;
for (const e of proposed) {
  if (e.strength < MIN_STRENGTH) continue;
  addEdge(e.a, e.b, 'recipenlg', e.strength);
  recipeCount++;
}

// 2. Base adjacency for analog inheritance = flavorbible (flavorPairings.ts) + recipenlg.
//    Built before analog edges are added, so analog never inherits from analog.
const base = new Map(); // node -> Map(neighbor -> strength|null)
const addBase = (a, b, s) => {
  if (!base.has(a)) base.set(a, new Map());
  const m = base.get(a);
  if (!m.has(b) || (s != null && (m.get(b) == null || s > m.get(b)))) m.set(b, s);
};
const fpSrc = fs.readFileSync(path.join(REPO_ROOT, 'src', 'data', 'flavorPairings.ts'), 'utf8');
for (const m of fpSrc.matchAll(/"([^"]+),([^"]+)"/g)) { addBase(m[1], m[2], null); addBase(m[2], m[1], null); }
for (const [k, e] of edges) { const [a, b] = k.split(','); addBase(a, b, e.strength); addBase(b, a, e.strength); }

// 3. analog edges: each target borrows its siblings' neighbors, tagged 'analog'.
//    NB: we deliberately do NOT emit a direct target<->sibling edge. An analog is a
//    *substitute* for its cousin (chili crisp ~ chili oil), not something you'd combine
//    with it — a direct edge just produces redundant near-synonym pairings.
const ANALOG_FLAVORBIBLE_STRENGTH = 3; // strength for an inherited unweighted flavorbible edge
const ANALOG_TOP_N = 30;               // cap inherited neighbors per sibling
const { analogs } = JSON.parse(fs.readFileSync(path.join(__dirname, 'analog.json'), 'utf8'));
let analogCount = 0;
for (const [target, siblings] of Object.entries(analogs)) {
  for (const sib of siblings) {
    const nbrs = base.get(sib);
    if (!nbrs) continue;
    const ranked = [...nbrs.entries()]
      .filter(([n]) => n !== target)
      .map(([n, s]) => [n, s == null ? ANALOG_FLAVORBIBLE_STRENGTH : s])
      .sort((x, y) => y[1] - x[1])
      .slice(0, ANALOG_TOP_N);
    for (const [n, s] of ranked) { addEdge(target, n, 'analog', s); analogCount++; }
  }
}

// 4. Emit, sources in canonical order.
const SRC_ORDER = ['flavorbible', 'recipenlg', 'flavordb', 'analog'];
const keys = [...edges.keys()].sort();
const entries = keys
  .map((k) => {
    const e = edges.get(k);
    const srcs = SRC_ORDER.filter((s) => e.sources.has(s));
    return `  ${JSON.stringify(k)}: { sources: ${JSON.stringify(srcs)}, strength: ${e.strength} },`;
  })
  .join('\n');

const metaPath = path.join(REPO_ROOT, 'src', 'data', 'pairingMeta.ts');
const current = fs.readFileSync(metaPath, 'utf8');
// Preserve everything before the pairingMeta declaration (types + pairKey + docs).
const splitAt = current.indexOf('export const pairingMeta');
if (splitAt < 0) {
  console.error('Could not find `export const pairingMeta` in pairingMeta.ts');
  process.exit(1);
}
const header = current.slice(0, splitAt);
const generated =
  `export const pairingMeta: Record<string, PairingInfo> = {\n` +
  `  // GENERATED by tooling/pairing-pipeline/merge.mjs — do not hand-edit.\n` +
  `  // Sources: recipenlg (min-strength ${MIN_STRENGTH}) + analog (analog.json). ${keys.length} edges.\n` +
  `${entries}\n};\n`;
const next = header + generated;

console.log(`recipenlg kept: ${recipeCount} | analog added: ${analogCount} | total edges: ${keys.length}`);
if (DRY) {
  console.log('--dry-run: not writing.');
} else {
  fs.writeFileSync(metaPath, next);
  console.log(`Wrote ${path.relative(REPO_ROOT, metaPath)}.`);
}
