#!/usr/bin/env node
// tooling/pairing-pipeline/merge-context.mjs
//
// Folds mined dish context (output/edge-context.json) into src/data/pairingContext.ts —
// the compact, shipped form of "what recipes is this pairing seen in?".
//
// Display policy lives HERE (context.mjs emits raw counts): a tag is kept only when it
// clears both an absolute count and a share-of-edge threshold, so one-off noise (an
// apple+cinnamon recipe that happened to be titled "Mexican Wassail") never ships.
//
// Shipped encoding, tuned for bundle size:
//   - three tag vocabularies (dish / method / cuisine) — display-ready strings
//   - a deduped title table (popular titles are shared by many edges)
//   - per edge: [recipeCount, dishIdxs, methodIdxs, cuisineIdxs, titleIdxs]
//
// Usage:
//   node merge-context.mjs [--min-edge 5] [--min-tag-count 3] [--min-tag-share 0.15]
//                          [--min-cuisine-share 0.1] [--max-titles 3] [--dry-run]
//
// Re-runnable: regenerates pairingContext.ts from scratch each time.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { REPO_ROOT, makeGetArg } from './lib.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const args = process.argv.slice(2);
const getArg = makeGetArg(args);
const MIN_EDGE = Number(getArg('min-edge', '5'));
const MIN_TAG_COUNT = Number(getArg('min-tag-count', '3'));
const MIN_TAG_SHARE = Number(getArg('min-tag-share', '0.15'));
const MIN_CUISINE_SHARE = Number(getArg('min-cuisine-share', '0.1'));
const MAX_TITLES = Number(getArg('max-titles', '2'));
const DRY = args.includes('--dry-run');

const { edges, recipesRead } = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'output', 'edge-context.json'), 'utf8'),
);

// ---- interners: stable index per distinct string ----
const makeInterner = () => {
  const list = [];
  const idx = new Map();
  return {
    list,
    intern: (s) => {
      if (!idx.has(s)) { idx.set(s, list.length); list.push(s); }
      return idx.get(s);
    },
  };
};
const dishI = makeInterner();
const methodI = makeInterner();
const cuisineI = makeInterner();
const titleI = makeInterner();

// Keep top tags that clear both floors. `counts` is [[tag, count], ...] sorted desc.
const keepTags = (counts, n, interner, maxKeep, minShare) =>
  counts
    .filter(([, c]) => c >= MIN_TAG_COUNT && c / n >= minShare)
    .slice(0, maxKeep)
    .map(([t]) => interner.intern(t));

const out = {};
let kept = 0;
for (const key of Object.keys(edges).sort()) {
  const e = edges[key];
  if (e.n < MIN_EDGE) continue;

  const dish = keepTags(e.dish, e.n, dishI, 3, MIN_TAG_SHARE);
  const method = keepTags(e.method, e.n, methodI, 3, MIN_TAG_SHARE);
  const cuisine = keepTags(e.cuisine, e.n, cuisineI, 2, MIN_CUISINE_SHARE);

  // Titles: rank for *prototypicality* — the receipt should read like a known dish
  // ("Tom Kha Gai", "Beef Stew"), not an 8-word blog flourish. Score = repeat sightings,
  // with a curated-domain bonus (editorial sites beat recipe mills) and a length penalty.
  // Eligible = seen twice with this pair, or seen once on a curated site. When an edge
  // has no eligible receipt, fall back to its top one-off title — rare edges are exactly
  // where a concrete receipt matters most.
  const lengthFactor = (t) => {
    const words = t.split(' ').length;
    return words <= 4 ? 1 : words <= 6 ? 0.6 : 0.3;
  };
  // Last-line title hygiene: some corpus titles are truncated mid-list ("Beef Chili
  // With Ancho,") — strip dangling punctuation/conjunctions before shipping.
  const tidyTitle = (t) => {
    const tidied = t
      .replace(/[\s,;:&+-]+$/, '')
      .replace(/\s+(with|and|or|in|for)$/i, '')
      .replace(/(['’])S\b/g, '$1s'); // title-caser artifact ("José'S", "J.P.'S"), straight or curly quote
    return tidied.length >= 3 ? tidied : null;
  };
  let titles = (e.titles || [])
    .filter(([, c, cur]) => c >= 2 || cur >= 1)
    .map(([t, c, cur]) => [tidyTitle(t), (c + 2 * cur) * lengthFactor(t)])
    .filter(([t]) => t)
    .sort((x, y) => y[1] - x[1])
    .slice(0, MAX_TITLES);
  if (titles.length === 0) {
    const fallback = e.titles?.[0]?.[0] ?? e.rare?.[0]?.[0];
    const tidied = fallback ? tidyTitle(fallback) : null;
    if (tidied) titles = [[tidied, 0]];
  }
  const titleIdxs = titles.map(([t]) => titleI.intern(t));

  if (dish.length + method.length + cuisine.length + titleIdxs.length === 0) continue;
  out[key] = [e.n, dish, method, cuisine, titleIdxs];
  kept++;
}

// ---- emit TypeScript ----
const entries = Object.keys(out)
  .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(out[k])},`)
  .join('\n');

const file = `// data/pairingContext.ts
//
// Dish context for pairing edges, mined from the RecipeNLG corpus (${recipesRead} recipes).
// GENERATED by tooling/pairing-pipeline/merge-context.mjs — do not hand-edit.
//
// This annotates edges the flavor graph already has (it never adds or scores edges):
// which kinds of dishes a pairing shows up in, how those dishes are cooked, which
// cuisines claim it, and a few concrete recipe titles as receipts.
//
// Encoding: per edge (key = pairKey(a, b)) a tuple
//   [recipeCount, dishTypeIdxs, methodIdxs, cuisineIdxs, titleIdxs]
// with indices into the string tables below. Decode via src/utils/pairingContext.ts.

export type PairingContextEntry = [
  /** recipes containing both ingredients */ number,
  /** indices into CONTEXT_DISH_TYPES */ number[],
  /** indices into CONTEXT_METHODS */ number[],
  /** indices into CONTEXT_CUISINES */ number[],
  /** indices into CONTEXT_TITLES */ number[],
];

export const CONTEXT_DISH_TYPES: string[] = ${JSON.stringify(dishI.list)};

export const CONTEXT_METHODS: string[] = ${JSON.stringify(methodI.list)};

export const CONTEXT_CUISINES: string[] = ${JSON.stringify(cuisineI.list)};

export const CONTEXT_TITLES: string[] = ${JSON.stringify(titleI.list)};

export const pairingContext: Record<string, PairingContextEntry> = {
${entries}
};
`;

const outPath = path.join(REPO_ROOT, 'src', 'data', 'pairingContext.ts');
const sizeKb = (Buffer.byteLength(file) / 1024).toFixed(0);
console.log(
  `edges kept: ${kept} | titles: ${titleI.list.length} | dish tags: ${dishI.list.length} | ` +
  `methods: ${methodI.list.length} | cuisines: ${cuisineI.list.length} | file: ${sizeKb} KB`,
);
if (DRY) {
  console.log('--dry-run: not writing.');
} else {
  fs.writeFileSync(outPath, file);
  console.log(`Wrote ${path.relative(REPO_ROOT, outPath)}.`);
}
