import Foundation
import Combine

/// ViewModel for menu builder
@MainActor
class MenuPlannerVM: ObservableObject {
    // MARK: - Published Properties

    @Published var configuration: MenuConfiguration = .default
    @Published var generatedMenu: Menu?
    @Published var isGenerating: Bool = false
    @Published var error: String?
    @Published var menuName: String = "Menu"
    @Published var loadedMenuId: UUID?  // Track if we're editing a loaded menu
    @Published var selectedDishTypes: [DishType: Int] = [:]  // Dish type counts for menu generation

    // MARK: - Dependencies

    private let menuGenerator: MenuGenerator
    private let ingredientService: IngredientService
    private let dietaryService: DietaryService

    // MARK: - Initialization

    init(menuGenerator: MenuGenerator, ingredientService: IngredientService, dietaryService: DietaryService) {
        self.menuGenerator = menuGenerator
        self.ingredientService = ingredientService
        self.dietaryService = dietaryService
    }

    // MARK: - Configuration

    @available(*, deprecated, message: "Use addKeyIngredient or setKeyIngredients instead")
    func setKeyIngredient(_ ingredient: String) {
        setKeyIngredients([ingredient])
    }

    /// Add a key ingredient (up to 3 maximum)
    func addKeyIngredient(_ ingredient: String) {
        guard !configuration.keyIngredients.contains(ingredient) else { return }
        guard configuration.keyIngredients.count < 3 else { return }

        configuration.keyIngredients.append(ingredient)
        updateMenuName()
        syncKeyIngredientsToMenu()
        // Don't clear dishes - preserve existing menu
    }

    /// Remove a key ingredient
    func removeKeyIngredient(_ ingredient: String) {
        configuration.keyIngredients.removeAll { $0 == ingredient }
        updateMenuName()
        syncKeyIngredientsToMenu()
        // Don't clear dishes
    }

    /// Set all key ingredients at once (replaces existing)
    func setKeyIngredients(_ ingredients: [String]) {
        configuration.keyIngredients = Array(ingredients.prefix(3))  // Max 3
        updateMenuName()
        // Sync to existing menu so pairing visualizations update
        syncKeyIngredientsToMenu()
    }

    /// Update menu name based on current key ingredients
    private func updateMenuName() {
        if configuration.keyIngredients.isEmpty {
            menuName = "Menu"
            if var menu = generatedMenu {
                menu.name = "Menu"
                generatedMenu = menu
            }
        } else if configuration.keyIngredients.count == 1 {
            menuName = "\(configuration.keyIngredients[0].capitalized) Menu"
            if var menu = generatedMenu {
                menu.name = menuName
                generatedMenu = menu
            }
        } else {
            let ingredientNames = configuration.keyIngredients.map { $0.capitalized }
            menuName = "\(ingredientNames.joined(separator: " & ")) Menu"
            if var menu = generatedMenu {
                menu.name = menuName
                generatedMenu = menu
            }
        }
    }

    /// Sync configuration's key ingredients to the generated menu
    /// This ensures pairing visualizations update when featured ingredients change
    private func syncKeyIngredientsToMenu() {
        guard var menu = generatedMenu else { return }
        menu.keyIngredients = configuration.keyIngredients
        generatedMenu = menu
    }

    /// Set custom menu name (user-provided, persists after saving/loading)
    func setMenuName(_ name: String) {
        menuName = name
        if var menu = generatedMenu {
            menu.name = name
            generatedMenu = menu
        }
    }

    /// Promote a dish ingredient to featured ingredient
    func promoteIngredientToFeatured(_ ingredient: String) {
        guard !configuration.keyIngredients.contains(ingredient) else { return }
        guard configuration.keyIngredients.count < 3 else { return }

        addKeyIngredient(ingredient)
    }

    func generateRandomKeyIngredient(autoGenerateDish: Bool = true) async {
        // Filter ingredients by dietary restrictions
        let filteredProfiles = dietaryService.filterProfiles(
            ingredientService.profiles,
            restrictions: configuration.dietaryRestrictions
        )

        // Further filter to only ingredients that have enough pairings to generate a dish
        // This excludes ingredients like Maldon Salt (0 pairings) or Rosé (too few pairings)
        let generatableProfiles = menuGenerator.filterGeneratableProfiles(
            filteredProfiles,
            restrictions: configuration.dietaryRestrictions
        )

        if let randomIngredient = generatableProfiles.randomElement() {
            setKeyIngredients([randomIngredient.name])
            // Automatically generate first dish with the selected ingredient (unless disabled)
            if autoGenerateDish {
                await addDish()
            }
        }
    }

    // MARK: - Dish Type Selection

    func incrementDishType(_ type: DishType) {
        selectedDishTypes[type, default: 0] += 1
    }

    func decrementDishType(_ type: DishType) {
        if let count = selectedDishTypes[type], count > 0 {
            selectedDishTypes[type] = count - 1
            if selectedDishTypes[type] == 0 {
                selectedDishTypes.removeValue(forKey: type)
            }
        }
    }

    func dishCount(for type: DishType) -> Int {
        selectedDishTypes[type] ?? 0
    }

    var totalDishCount: Int {
        selectedDishTypes.values.reduce(0, +)
    }

    // MARK: - Full Menu Generation

    func generateFullMenu() async {
        // In freeform mode, we don't need key ingredients
        if configuration.compatibilityMode != .freeform {
            guard !configuration.keyIngredients.isEmpty else { return }
        }
        guard totalDishCount > 0 else { return }

        isGenerating = true

        // Create new menu
        let keyIngredients = configuration.keyIngredients.isEmpty ? [] : configuration.keyIngredients
        generatedMenu = Menu(
            name: menuName,
            keyIngredients: keyIngredients,
            dishes: [],
            dietaryRestrictions: configuration.dietaryRestrictions,
            compatibilityMode: configuration.compatibilityMode
        )

        // Sort dish types by priority (entree first, then others)
        let sortedTypes = selectedDishTypes.keys.sorted { a, b in
            dishTypePriority(a) < dishTypePriority(b)
        }

        // Track if this is the first dish (to include key ingredient)
        var isFirstDish = true

        // Generate dishes for each selected type
        for dishType in sortedTypes {
            let count = selectedDishTypes[dishType] ?? 0
            for _ in 0..<count {
                // In freeform mode, never include the key ingredient
                let shouldIncludeKeyIngredient = configuration.compatibilityMode != .freeform && isFirstDish

                if let dish = menuGenerator.generateDishWithFormula(
                    type: dishType,
                    keyIngredients: keyIngredients,
                    restrictions: configuration.dietaryRestrictions,
                    compatibilityMode: configuration.compatibilityMode,
                    includeKeyIngredient: shouldIncludeKeyIngredient
                ) {
                    generatedMenu?.dishes.append(dish)
                    isFirstDish = false
                }
            }
        }

        isGenerating = false

        // Clear selections after generation
        selectedDishTypes = [:]
    }

    private func dishTypePriority(_ type: DishType) -> Int {
        switch type {
        case .entree: return 0
        case .side: return 1
        case .salad: return 2
        case .sauce: return 3
        case .dessert: return 4
        case .beverage: return 5
        }
    }

    // MARK: - Dish Management

    func addDish() async {
        // In freeform mode, we don't need key ingredients
        if configuration.compatibilityMode != .freeform {
            guard !configuration.keyIngredients.isEmpty else { return }
        }

        isGenerating = true

        // Determine if this is the first dish
        let isFirstDish = generatedMenu?.dishes.isEmpty ?? true

        // Use configured key ingredients (empty array for freeform mode)
        let keyIngredients = configuration.keyIngredients

        // In freeform mode, never include the key ingredient in the dish
        // In other modes, include it only for the first dish
        let shouldIncludeKeyIngredient = configuration.compatibilityMode != .freeform && isFirstDish

        if let newDish = menuGenerator.generateSingleDish(
            keyIngredients: keyIngredients,
            existingDishes: generatedMenu?.dishes ?? [],
            restrictions: configuration.dietaryRestrictions,
            includeKeyIngredient: shouldIncludeKeyIngredient,
            compatibilityMode: configuration.compatibilityMode
        ) {
            if generatedMenu == nil {
                // Create a new menu
                updateMenuName()  // Ensure menu name is up to date
                generatedMenu = Menu(
                    name: menuName,
                    keyIngredients: keyIngredients,
                    dishes: [newDish],
                    dietaryRestrictions: configuration.dietaryRestrictions,
                    compatibilityMode: configuration.compatibilityMode
                )
            } else {
                generatedMenu?.dishes.append(newDish)
            }
        }

        isGenerating = false
    }

    func addDishWithIngredient(_ pairedIngredient: String) async {
        guard !configuration.keyIngredients.isEmpty else { return }

        isGenerating = true

        // Determine if this is the first dish
        let isFirstDish = generatedMenu?.dishes.isEmpty ?? true

        // Generate a dish with both the key ingredients and the paired ingredient
        if let newDish = menuGenerator.generateSingleDish(
            keyIngredients: configuration.keyIngredients,
            existingDishes: generatedMenu?.dishes ?? [],
            restrictions: configuration.dietaryRestrictions,
            includeKeyIngredient: isFirstDish,
            requiredIngredient: pairedIngredient,
            compatibilityMode: configuration.compatibilityMode
        ) {
            if generatedMenu == nil {
                // Create a new menu
                updateMenuName()
                generatedMenu = Menu(
                    name: menuName,
                    keyIngredients: configuration.keyIngredients,
                    dishes: [newDish],
                    dietaryRestrictions: configuration.dietaryRestrictions,
                    compatibilityMode: configuration.compatibilityMode
                )
            } else {
                generatedMenu?.dishes.append(newDish)
            }
        }

        isGenerating = false
    }

    /// Creates a dish with only the selected ingredient (for Build Dish flow)
    /// Returns the created dish so it can be opened in the editor
    func createDishWithIngredient(_ selectedIngredient: String) -> Dish {
        // Calculate taste profile for the single ingredient
        let profile = ingredientService.getProfile(selectedIngredient)
        let tasteProfile = profile?.flavorProfile ?? .zero

        // Create dish with just the selected ingredient
        let newDish = Dish(
            name: Dish.generateName(keyIngredient: selectedIngredient, type: nil, mainIngredients: []),
            type: nil,
            keyIngredient: selectedIngredient,
            ingredients: [],
            tasteProfile: tasteProfile,
            weight: 5
        )

        // Add to menu
        if generatedMenu == nil {
            updateMenuName()
            generatedMenu = Menu(
                name: menuName,
                keyIngredients: configuration.keyIngredients,
                dishes: [newDish],
                dietaryRestrictions: configuration.dietaryRestrictions,
                compatibilityMode: configuration.compatibilityMode
            )
        } else {
            generatedMenu?.dishes.append(newDish)
        }

        return newDish
    }

    func deleteDish(_ dish: Dish) {
        generatedMenu?.dishes.removeAll { $0.id == dish.id }

        // Clear menu if no dishes left
        if generatedMenu?.dishes.isEmpty == true {
            generatedMenu = nil
        }
    }

    func updateDish(_ dish: Dish) {
        guard let index = generatedMenu?.dishes.firstIndex(where: { $0.id == dish.id }) else { return }
        generatedMenu?.dishes[index] = dish
    }

    func regenerateDish(_ dish: Dish) async {
        guard let menu = generatedMenu else { return }

        isGenerating = true

        // Check if this is the first dish (should include key ingredient)
        let isFirstDish = menu.dishes.first?.id == dish.id

        // In freeform mode, never include the key ingredient (since it's just "freeform")
        // In other modes, include it only for the first dish
        let shouldIncludeKeyIngredient = configuration.compatibilityMode != .freeform && isFirstDish

        if let newDish = menuGenerator.regenerateSingleDish(
            dish: dish,
            in: menu,
            restrictions: configuration.dietaryRestrictions,
            includeKeyIngredient: shouldIncludeKeyIngredient,
            compatibilityMode: configuration.compatibilityMode
        ) {
            if let index = generatedMenu?.dishes.firstIndex(where: { $0.id == dish.id }) {
                generatedMenu?.dishes[index] = newDish
            }
        }

        isGenerating = false
    }

    // MARK: - Load Menu

    func loadMenu(_ menu: Menu, menuId: UUID? = nil) {
        print("🔍 Loading menu: \(menu.name)")
        print("🔍 Dietary restrictions from menu: \(menu.dietaryRestrictions)")
        print("🔍 Compatibility mode from menu: \(menu.compatibilityMode)")

        configuration.keyIngredients = menu.keyIngredients
        configuration.dietaryRestrictions = menu.dietaryRestrictions
        configuration.compatibilityMode = menu.compatibilityMode
        generatedMenu = menu
        menuName = menu.name
        loadedMenuId = menuId

        print("🔍 Configuration after load - dietary: \(configuration.dietaryRestrictions)")
        print("🔍 Configuration after load - mode: \(configuration.compatibilityMode)")
    }

    // MARK: - Sync Configuration

    /// Sync current configuration to the generated menu
    /// Call this when configuration changes (e.g., dietary restrictions updated in settings)
    func syncConfigurationToMenu() {
        guard var menu = generatedMenu else { return }
        menu.dietaryRestrictions = configuration.dietaryRestrictions
        menu.compatibilityMode = configuration.compatibilityMode
        generatedMenu = menu
        print("🔄 Synced configuration to menu - dietary: \(menu.dietaryRestrictions), mode: \(menu.compatibilityMode)")
    }

    // MARK: - Recipe URL Import

    /// Create a dish from a recipe URL (Phase 1: manual ingredient selection)
    func createDishFromRecipeURL(_ url: String, title: String?) {
        // Create dish with empty ingredients - user will add manually
        let newDish = Dish(
            name: title ?? "New Dish",
            type: nil,
            keyIngredient: "",  // Will be set when user adds first ingredient
            ingredients: [],
            recipeURL: URL(string: url),
            recipeImageURL: nil,
            recipeTitle: title
        )

        if var menu = generatedMenu {
            menu.dishes.append(newDish)
            generatedMenu = menu
        } else {
            // Create new menu if none exists
            updateMenuName()
            generatedMenu = Menu(
                name: menuName,
                keyIngredients: configuration.keyIngredients,
                dishes: [newDish],
                dietaryRestrictions: configuration.dietaryRestrictions,
                compatibilityMode: configuration.compatibilityMode
            )
        }
    }

    // MARK: - Reset

    func reset() {
        configuration = .default
        generatedMenu = nil
        error = nil
        menuName = "Menu"
        loadedMenuId = nil
        selectedDishTypes = [:]
    }

    // MARK: - Helpers

    func getIngredientSuggestions(query: String) -> [IngredientProfile] {
        if query.isEmpty {
            return ingredientService.profiles
        }
        return ingredientService.search(query)
    }
}
